<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;

class VisiteurSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('visiteurs')->insert(array(
            array(
                'VIS_MATRICULE' => 'a131',
                'VIS_NOM' => 'Villechalane',
                'VIS_PRENOM' => 'Louis',
                'VIS_ADRESSE' => '8 cours Lafontaine',
                'VIS_CP' => '29000',
                'VIS_VILLE' => 'BREST',
                'VIS_DATEEMBAUCHE' => '1992-12-11 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'SW',
            ),
            array(
                'VIS_MATRICULE' => 'a17',
                'VIS_NOM' => 'Andre',
                'VIS_PRENOM' => 'David',
                'VIS_ADRESSE' => '1 r Aimon de Chissée',
                'VIS_CP' => '38100',
                'VIS_VILLE' => 'GRENOBLE',
                'VIS_DATEEMBAUCHE' => '1991-08-26 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'GY',
            ),
            array(
                'VIS_MATRICULE' => 'a55',
                'VIS_NOM' => 'Bedos',
                'VIS_PRENOM' => 'Christian',
                'VIS_ADRESSE' => '1 r Bénédictins',
                'VIS_CP' => '65000',
                'VIS_VILLE' => 'TARBES',
                'VIS_DATEEMBAUCHE' => '1987-07-17 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'GY',
            ),
            array(
                'VIS_MATRICULE' => 'a93',
                'VIS_NOM' => 'Tusseau',
                'VIS_PRENOM' => 'Louis',
                'VIS_ADRESSE' => '22 r Renou',
                'VIS_CP' => '86000',
                'VIS_VILLE' => 'POITIERS',
                'VIS_DATEEMBAUCHE' => '1999-01-02 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'SW',
            ),
            array(
                'VIS_MATRICULE' => 'b13',
                'VIS_NOM' => 'Bentot',
                'VIS_PRENOM' => 'Pascal',
                'VIS_ADRESSE' => '11 av 6 Juin',
                'VIS_CP' => '67000',
                'VIS_VILLE' => 'STRASBOURG',
                'VIS_DATEEMBAUCHE' => '1996-03-11 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'GY',
            ),
            array(
                'VIS_MATRICULE' => 'b16',
                'VIS_NOM' => 'Bioret',
                'VIS_PRENOM' => 'Luc',
                'VIS_ADRESSE' => '1 r Linne',
                'VIS_CP' => '35000',
                'VIS_VILLE' => 'RENNES',
                'VIS_DATEEMBAUCHE' => '1997-03-21 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'SW',
            ),
            array(
                'VIS_MATRICULE' => 'b19',
                'VIS_NOM' => 'Bunisset',
                'VIS_PRENOM' => 'Francis',
                'VIS_ADRESSE' => '10 r Nicolas Chorier',
                'VIS_CP' => '85000',
                'VIS_VILLE' => 'La ROCHE SUR YON',
                'VIS_DATEEMBAUCHE' => '1999-01-31 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'GY',
            ),
            array(
                'VIS_MATRICULE' => 'b25',
                'VIS_NOM' => 'Bunisset',
                'VIS_PRENOM' => 'Denise',
                'VIS_ADRESSE' => '1 r Lionne',
                'VIS_CP' => '49100',
                'VIS_VILLE' => 'ANGERS',
                'VIS_DATEEMBAUCHE' => '1994-07-03 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'SW',
            ),
            array(
                'VIS_MATRICULE' => 'b28',
                'VIS_NOM' => 'Cacheux',
                'VIS_PRENOM' => 'Bernard',
                'VIS_ADRESSE' => '114 r Authie',
                'VIS_CP' => '34000',
                'VIS_VILLE' => 'MONTPELLIER',
                'VIS_DATEEMBAUCHE' => '2000-08-02 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'GY',
            ),
            array(
                'VIS_MATRICULE' => 'b34',
                'VIS_NOM' => 'Cadic',
                'VIS_PRENOM' => 'Eric',
                'VIS_ADRESSE' => '123 r Caponière',
                'VIS_CP' => '41000',
                'VIS_VILLE' => 'BLOIS',
                'VIS_DATEEMBAUCHE' => '1993-12-06 00:00:00',
                'SEC_CODE' => 'P',
                'LAB_CODE' => 'SW',
            ),
            array(
                'VIS_MATRICULE' => 'b4',
                'VIS_NOM' => 'Charoze',
                'VIS_PRENOM' => 'Catherine',
                'VIS_ADRESSE' => '100 pl Géants',
                'VIS_CP' => '33000',
                'VIS_VILLE' => 'BORDEAUX',
                'VIS_DATEEMBAUCHE' => '1997-09-25 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'SW',
            ),
            array(
                'VIS_MATRICULE' => 'b50',
                'VIS_NOM' => 'Clepkens',
                'VIS_PRENOM' => 'Christophe',
                'VIS_ADRESSE' => '12 r Fédérico Garcia Lorca',
                'VIS_CP' => '13000',
                'VIS_VILLE' => 'MARSEILLE',
                'VIS_DATEEMBAUCHE' => '1998-01-18 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'SW',
            ),
            array(
                'VIS_MATRICULE' => 'b59',
                'VIS_NOM' => 'Cottin',
                'VIS_PRENOM' => 'Vincenne',
                'VIS_ADRESSE' => '36 sq Capucins',
                'VIS_CP' => '05000',
                'VIS_VILLE' => 'GAP',
                'VIS_DATEEMBAUCHE' => '1995-10-21 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'GY',
            ),
            array(
                'VIS_MATRICULE' => 'c14',
                'VIS_NOM' => 'Daburon',
                'VIS_PRENOM' => 'François',
                'VIS_ADRESSE' => '13 r Champs Elysées',
                'VIS_CP' => '06000',
                'VIS_VILLE' => 'NICE',
                'VIS_DATEEMBAUCHE' => '1989-02-01 00:00:00',
                'SEC_CODE' => 'S',
                'LAB_CODE' => 'SW',
            ),
            array(
                'VIS_MATRICULE' => 'c3',
                'VIS_NOM' => 'De',
                'VIS_PRENOM' => 'Philippe',
                'VIS_ADRESSE' => '13 r Charles Peguy',
                'VIS_CP' => '10000',
                'VIS_VILLE' => 'Troyes',
                'VIS_DATEEMBAUCHE' => '1992-05-05 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'SW',
            ),
            array(
                'VIS_MATRICULE' => 'c54',
                'VIS_NOM' => 'Debelle',
                'VIS_PRENOM' => 'Michel',
                'VIS_ADRESSE' => '181 r Caponière',
                'VIS_CP' => '88000',
                'VIS_VILLE' => 'EPINAL',
                'VIS_DATEEMBAUCHE' => '1991-04-09 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'SW',
            ),
            array(
                'VIS_MATRICULE' => 'd13',
                'VIS_NOM' => 'Debelle',
                'VIS_PRENOM' => 'Jeanne',
                'VIS_ADRESSE' => '134 r Stalingrad',
                'VIS_CP' => '44000',
                'VIS_VILLE' => 'NANTES',
                'VIS_DATEEMBAUCHE' => '1991-12-05 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'SW',
            ),
            array(
                'VIS_MATRICULE' => 'd51',
                'VIS_NOM' => 'Debroise',
                'VIS_PRENOM' => 'Michel',
                'VIS_ADRESSE' => '2 av 6 Juin',
                'VIS_CP' => '70000',
                'VIS_VILLE' => 'VESOUL',
                'VIS_DATEEMBAUCHE' => '1997-11-18 00:00:00',
                'SEC_CODE' => 'E',
                'LAB_CODE' => 'GY',
            ),
            array(
                'VIS_MATRICULE' => 'e22',
                'VIS_NOM' => 'Desmarquest',
                'VIS_PRENOM' => 'Nathalie',
                'VIS_ADRESSE' => '14 r Fédérico Garcia Lorca',
                'VIS_CP' => '54000',
                'VIS_VILLE' => 'NANCY',
                'VIS_DATEEMBAUCHE' => '1989-03-24 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'GY',
            ),
            array(
                'VIS_MATRICULE' => 'e24',
                'VIS_NOM' => 'Desnost',
                'VIS_PRENOM' => 'Pierre',
                'VIS_ADRESSE' => '16 r Barral de Montferrat',
                'VIS_CP' => '55000',
                'VIS_VILLE' => 'VERDUN',
                'VIS_DATEEMBAUCHE' => '1993-05-17 00:00:00',
                'SEC_CODE' => 'E',
                'LAB_CODE' => 'SW',
            ),
            array(
                'VIS_MATRICULE' => 'e39',
                'VIS_NOM' => 'Dudouit',
                'VIS_PRENOM' => 'Frédéric',
                'VIS_ADRESSE' => '18 quai Xavier Jouvin',
                'VIS_CP' => '75000',
                'VIS_VILLE' => 'PARIS',
                'VIS_DATEEMBAUCHE' => '1988-04-26 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'GY',
            ),
            array(
                'VIS_MATRICULE' => 'e49',
                'VIS_NOM' => 'Duncombe',
                'VIS_PRENOM' => 'Claude',
                'VIS_ADRESSE' => '19 av Alsace Lorraine',
                'VIS_CP' => '09000',
                'VIS_VILLE' => 'FOIX',
                'VIS_DATEEMBAUCHE' => '1996-02-19 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'GY',
            ),
            array(
                'VIS_MATRICULE' => 'e5',
                'VIS_NOM' => 'Enault-Pascreau',
                'VIS_PRENOM' => 'Céline',
                'VIS_ADRESSE' => '25B r Stalingrad',
                'VIS_CP' => '40000',
                'VIS_VILLE' => 'MONT DE MARSAN',
                'VIS_DATEEMBAUCHE' => '1990-11-27 00:00:00',
                'SEC_CODE' => 'S',
                'LAB_CODE' => 'GY',
            ),
            array(
                'VIS_MATRICULE' => 'e52',
                'VIS_NOM' => 'Eynde',
                'VIS_PRENOM' => 'Valérie',
                'VIS_ADRESSE' => '3 r Henri Moissan',
                'VIS_CP' => '76000',
                'VIS_VILLE' => 'ROUEN',
                'VIS_DATEEMBAUCHE' => '1991-10-31 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'GY',
            ),
            array(
                'VIS_MATRICULE' => 'f21',
                'VIS_NOM' => 'Finck',
                'VIS_PRENOM' => 'Jacques',
                'VIS_ADRESSE' => 'rte Montreuil Bellay',
                'VIS_CP' => '74000',
                'VIS_VILLE' => 'ANNECY',
                'VIS_DATEEMBAUCHE' => '1993-06-08 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'SW',
            ),
            array(
                'VIS_MATRICULE' => 'f39',
                'VIS_NOM' => 'Frémont',
                'VIS_PRENOM' => 'Fernande',
                'VIS_ADRESSE' => '4 r Jean Giono',
                'VIS_CP' => '69000',
                'VIS_VILLE' => 'LYON',
                'VIS_DATEEMBAUCHE' => '1997-02-15 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'GY',
            ),
            array(
                'VIS_MATRICULE' => 'f4',
                'VIS_NOM' => 'Gest',
                'VIS_PRENOM' => 'Alain',
                'VIS_ADRESSE' => '30 r Authie',
                'VIS_CP' => '46000',
                'VIS_VILLE' => 'FIGEAC',
                'VIS_DATEEMBAUCHE' => '1994-05-03 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'GY',
            ),
            array(
                'VIS_MATRICULE' => 'g19',
                'VIS_NOM' => 'Gheysen',
                'VIS_PRENOM' => 'Galassus',
                'VIS_ADRESSE' => '32 bd Mar Foch',
                'VIS_CP' => '75000',
                'VIS_VILLE' => 'PARIS',
                'VIS_DATEEMBAUCHE' => '1996-01-18 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'SW',
            ),
            array(
                'VIS_MATRICULE' => 'g30',
                'VIS_NOM' => 'Girard',
                'VIS_PRENOM' => 'Yvon',
                'VIS_ADRESSE' => '31 av 6 Juin',
                'VIS_CP' => '80000',
                'VIS_VILLE' => 'AMIENS',
                'VIS_DATEEMBAUCHE' => '1999-03-27 00:00:00',
                'SEC_CODE' => 'N',
                'LAB_CODE' => 'GY',
            ),
            array(
                'VIS_MATRICULE' => 'g53',
                'VIS_NOM' => 'Gombert',
                'VIS_PRENOM' => 'Luc',
                'VIS_ADRESSE' => '32 r Emile Gueymard',
                'VIS_CP' => '56000',
                'VIS_VILLE' => 'VANNES',
                'VIS_DATEEMBAUCHE' => '1985-10-02 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'GY',
            ),
            array(
                'VIS_MATRICULE' => 'g7',
                'VIS_NOM' => 'Guindon',
                'VIS_PRENOM' => 'Caroline',
                'VIS_ADRESSE' => '40 r Mar Montgomery',
                'VIS_CP' => '87000',
                'VIS_VILLE' => 'LIMOGES',
                'VIS_DATEEMBAUCHE' => ' 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'GY',
            ),
            array(
                'VIS_MATRICULE' => 'h13',
                'VIS_NOM' => 'Guindon',
                'VIS_PRENOM' => 'François',
                'VIS_ADRESSE' => '44 r Picotière',
                'VIS_CP' => '19000',
                'VIS_VILLE' => 'TULLE',
                'VIS_DATEEMBAUCHE' => '1993-05-08 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'SW',
            ),
            array(
                'VIS_MATRICULE' => 'h30',
                'VIS_NOM' => 'Igigabel',
                'VIS_PRENOM' => 'Guy',
                'VIS_ADRESSE' => '33 gal Arlequin',
                'VIS_CP' => '94000',
                'VIS_VILLE' => 'CRETEIL',
                'VIS_DATEEMBAUCHE' => '1998-04-26 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'SW',
            ),
            array(
                'VIS_MATRICULE' => 'h35',
                'VIS_NOM' => 'Jourdren',
                'VIS_PRENOM' => 'Pierre',
                'VIS_ADRESSE' => '34 av Jean Perrot',
                'VIS_CP' => '15000',
                'VIS_VILLE' => 'AURRILLAC',
                'VIS_DATEEMBAUCHE' => '1993-08-26 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'GY',
            ),
            array(
                'VIS_MATRICULE' => 'h40',
                'VIS_NOM' => 'Juttard',
                'VIS_PRENOM' => 'Pierre-Raoul',
                'VIS_ADRESSE' => '34 cours Jean Jaurès',
                'VIS_CP' => '08000',
                'VIS_VILLE' => 'SEDAN',
                'VIS_DATEEMBAUCHE' => '1992-11-01 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'GY',
            ),
            array(
                'VIS_MATRICULE' => 'j45',
                'VIS_NOM' => 'Labouré-Morel',
                'VIS_PRENOM' => 'Saout',
                'VIS_ADRESSE' => '38 cours Berriat',
                'VIS_CP' => '52000',
                'VIS_VILLE' => 'CHAUMONT',
                'VIS_DATEEMBAUCHE' => '1998-02-25 00:00:00',
                'SEC_CODE' => 'N',
                'LAB_CODE' => 'SW',
            ),
            array(
                'VIS_MATRICULE' => 'j50',
                'VIS_NOM' => 'Landré',
                'VIS_PRENOM' => 'Philippe',
                'VIS_ADRESSE' => '4 av Gén Laperrine',
                'VIS_CP' => '59000',
                'VIS_VILLE' => 'LILLE',
                'VIS_DATEEMBAUCHE' => '1992-12-16 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'GY',
            ),
            array(
                'VIS_MATRICULE' => 'j8',
                'VIS_NOM' => 'Langeard',
                'VIS_PRENOM' => 'Hugues',
                'VIS_ADRESSE' => '39 av Jean Perrot',
                'VIS_CP' => '93000',
                'VIS_VILLE' => 'BAGNOLET',
                'VIS_DATEEMBAUCHE' => '1998-06-18 00:00:00',
                'SEC_CODE' => 'P',
                'LAB_CODE' => 'GY',
            ),
            array(
                'VIS_MATRICULE' => 'k4',
                'VIS_NOM' => 'Lanne',
                'VIS_PRENOM' => 'Bernard',
                'VIS_ADRESSE' => '4 r Bayeux',
                'VIS_CP' => '30000',
                'VIS_VILLE' => 'NIMES',
                'VIS_DATEEMBAUCHE' => '1996-11-21 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'SW',
            ),
            array(
                'VIS_MATRICULE' => 'k53',
                'VIS_NOM' => 'Le',
                'VIS_PRENOM' => 'Noël',
                'VIS_ADRESSE' => '4 av Beauvert',
                'VIS_CP' => '68000',
                'VIS_VILLE' => 'MULHOUSE',
                'VIS_DATEEMBAUCHE' => '1983-03-23 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'SW',
            ),
            array(
                'VIS_MATRICULE' => 'l14',
                'VIS_NOM' => 'Le',
                'VIS_PRENOM' => 'Jean',
                'VIS_ADRESSE' => '39 r Raspail',
                'VIS_CP' => '53000',
                'VIS_VILLE' => 'LAVAL',
                'VIS_DATEEMBAUCHE' => '1995-02-02 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'SW',
            ),
            array(
                'VIS_MATRICULE' => 'l23',
                'VIS_NOM' => 'Leclercq',
                'VIS_PRENOM' => 'Servane',
                'VIS_ADRESSE' => '11 r Quinconce',
                'VIS_CP' => '18000',
                'VIS_VILLE' => 'BOURGES',
                'VIS_DATEEMBAUCHE' => '1995-06-05 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'SW',
            ),
            array(
                'VIS_MATRICULE' => 'l46',
                'VIS_NOM' => 'Lecornu',
                'VIS_PRENOM' => 'Jean-Bernard',
                'VIS_ADRESSE' => '4 bd Mar Foch',
                'VIS_CP' => '72000',
                'VIS_VILLE' => 'LA FERTE BERNARD',
                'VIS_DATEEMBAUCHE' => '1997-01-24 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'GY',
            ),
            array(
                'VIS_MATRICULE' => 'l56',
                'VIS_NOM' => 'Lecornu',
                'VIS_PRENOM' => 'Ludovic',
                'VIS_ADRESSE' => '4 r Abel Servien',
                'VIS_CP' => '25000',
                'VIS_VILLE' => 'BESANCON',
                'VIS_DATEEMBAUCHE' => '1996-02-27 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'SW',
            ),
            array(
                'VIS_MATRICULE' => 'm35',
                'VIS_NOM' => 'Lejard',
                'VIS_PRENOM' => 'Agnès',
                'VIS_ADRESSE' => '4 r Anthoard',
                'VIS_CP' => '82000',
                'VIS_VILLE' => 'MONTAUBAN',
                'VIS_DATEEMBAUCHE' => '1987-10-06 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'SW',
            ),
            array(
                'VIS_MATRICULE' => 'm45',
                'VIS_NOM' => 'Lesaulnier',
                'VIS_PRENOM' => 'Pascal',
                'VIS_ADRESSE' => '47 r Thiers',
                'VIS_CP' => '57000',
                'VIS_VILLE' => 'METZ',
                'VIS_DATEEMBAUCHE' => '1990-10-13 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'SW',
            ),
            array(
                'VIS_MATRICULE' => 'n42',
                'VIS_NOM' => 'Letessier',
                'VIS_PRENOM' => 'Stéphane',
                'VIS_ADRESSE' => '5 chem Capuche',
                'VIS_CP' => '27000',
                'VIS_VILLE' => 'EVREUX',
                'VIS_DATEEMBAUCHE' => '1996-03-06 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'GY',
            ),
            array(
                'VIS_MATRICULE' => 'n58',
                'VIS_NOM' => 'Loirat',
                'VIS_PRENOM' => 'Didier',
                'VIS_ADRESSE' => 'Les Pêchers cité Bourg la Croix',
                'VIS_CP' => '45000',
                'VIS_VILLE' => 'ORLEANS',
                'VIS_DATEEMBAUCHE' => '1992-08-30 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'GY',
            ),
            array(
                'VIS_MATRICULE' => 'n59',
                'VIS_NOM' => 'Maffezzoli',
                'VIS_PRENOM' => 'Thibaud',
                'VIS_ADRESSE' => '5 r Chateaubriand',
                'VIS_CP' => '02000',
                'VIS_VILLE' => 'LAON',
                'VIS_DATEEMBAUCHE' => '1994-12-19 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'SW',
            ),
            array(
                'VIS_MATRICULE' => 'o26',
                'VIS_NOM' => 'Mancini',
                'VIS_PRENOM' => 'Anne',
                'VIS_ADRESSE' => '5 r d\'Agier',
                'VIS_CP' => '48000',
                'VIS_VILLE' => 'MENDE',
                'VIS_DATEEMBAUCHE' => '1995-01-05 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'GY',
            ),
            array(
                'VIS_MATRICULE' => 'p32',
                'VIS_NOM' => 'Marcouiller',
                'VIS_PRENOM' => 'Gérard',
                'VIS_ADRESSE' => '7 pl St Gilles',
                'VIS_CP' => '91000',
                'VIS_VILLE' => 'ISSY LES MOULINEAUX',
                'VIS_DATEEMBAUCHE' => '1992-12-24 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'GY',
            ),
            array(
                'VIS_MATRICULE' => 'p40',
                'VIS_NOM' => 'Michel',
                'VIS_PRENOM' => 'Jean-Claude',
                'VIS_ADRESSE' => '5 r Gabriel Péri',
                'VIS_CP' => '61000',
                'VIS_VILLE' => 'FLERS',
                'VIS_DATEEMBAUCHE' => '1992-12-14 00:00:00',
                'SEC_CODE' => 'O',
                'LAB_CODE' => 'SW',
            ),
            array(
                'VIS_MATRICULE' => 'p41',
                'VIS_NOM' => 'Montecot',
                'VIS_PRENOM' => 'Françoise',
                'VIS_ADRESSE' => '6 r Paul Valéry',
                'VIS_CP' => '17000',
                'VIS_VILLE' => 'SAINTES',
                'VIS_DATEEMBAUCHE' => '1998-07-27 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'GY',
            ),
            array(
                'VIS_MATRICULE' => 'p42',
                'VIS_NOM' => 'Notini',
                'VIS_PRENOM' => 'Veronique',
                'VIS_ADRESSE' => '5 r Lieut Chabal',
                'VIS_CP' => '60000',
                'VIS_VILLE' => 'BEAUVAIS',
                'VIS_DATEEMBAUCHE' => '1994-12-12 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'SW',
            ),
            array(
                'VIS_MATRICULE' => 'p49',
                'VIS_NOM' => 'Onfroy',
                'VIS_PRENOM' => 'Den',
                'VIS_ADRESSE' => '5 r Sidonie Jacolin',
                'VIS_CP' => '37000',
                'VIS_VILLE' => 'TOURS',
                'VIS_DATEEMBAUCHE' => '1977-10-03 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'GY',
            ),
            array(
                'VIS_MATRICULE' => 'p6',
                'VIS_NOM' => 'Pascreau',
                'VIS_PRENOM' => 'Charles',
                'VIS_ADRESSE' => '57 bd Mar Foch',
                'VIS_CP' => '64000',
                'VIS_VILLE' => 'PAU',
                'VIS_DATEEMBAUCHE' => '1997-03-30 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'SW',
            ),
            array(
                'VIS_MATRICULE' => 'p7',
                'VIS_NOM' => 'Pernot',
                'VIS_PRENOM' => 'Claude-Noël',
                'VIS_ADRESSE' => '6 r Alexandre 1 de Yougoslavie',
                'VIS_CP' => '11000',
                'VIS_VILLE' => 'NARBONNE',
                'VIS_DATEEMBAUCHE' => '1990-03-01 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'SW',
            ),
            array(
                'VIS_MATRICULE' => 'p8',
                'VIS_NOM' => 'Perrier',
                'VIS_PRENOM' => 'Maître',
                'VIS_ADRESSE' => '6 r Aubert Dubayet',
                'VIS_CP' => '71000',
                'VIS_VILLE' => 'CHALON SUR SAONE',
                'VIS_DATEEMBAUCHE' => '1991-06-23 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'GY',
            ),
            array(
                'VIS_MATRICULE' => 'q17',
                'VIS_NOM' => 'Petit',
                'VIS_PRENOM' => 'Jean-Louis',
                'VIS_ADRESSE' => '7 r Ernest Renan',
                'VIS_CP' => '50000',
                'VIS_VILLE' => 'SAINT LO',
                'VIS_DATEEMBAUCHE' => '1997-09-06 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'GY',
            ),
            array(
                'VIS_MATRICULE' => 'r24',
                'VIS_NOM' => 'Piquery',
                'VIS_PRENOM' => 'Patrick',
                'VIS_ADRESSE' => '9 r Vaucelles',
                'VIS_CP' => '14000',
                'VIS_VILLE' => 'CAEN',
                'VIS_DATEEMBAUCHE' => '1984-07-29 00:00:00',
                'SEC_CODE' => 'O',
                'LAB_CODE' => 'GY',
            ),
            array(
                'VIS_MATRICULE' => 'r58',
                'VIS_NOM' => 'Quiquandon',
                'VIS_PRENOM' => 'Joël',
                'VIS_ADRESSE' => '7 r Ernest Renan',
                'VIS_CP' => '29000',
                'VIS_VILLE' => 'QUIMPER',
                'VIS_DATEEMBAUCHE' => '1990-06-30 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'GY',
            ),
            array(
                'VIS_MATRICULE' => 's10',
                'VIS_NOM' => 'Retailleau',
                'VIS_PRENOM' => 'Josselin',
                'VIS_ADRESSE' => '88Bis r Saumuroise',
                'VIS_CP' => '39000',
                'VIS_VILLE' => 'DOLE',
                'VIS_DATEEMBAUCHE' => '1995-11-14 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'SW',
            ),
            array(
                'VIS_MATRICULE' => 's21',
                'VIS_NOM' => 'Retailleau',
                'VIS_PRENOM' => 'Pascal',
                'VIS_ADRESSE' => '32 bd Ayrault',
                'VIS_CP' => '23000',
                'VIS_VILLE' => 'MONTLUCON',
                'VIS_DATEEMBAUCHE' => '1992-09-25 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'SW',
            ),
            array(
                'VIS_MATRICULE' => 't43',
                'VIS_NOM' => 'Souron',
                'VIS_PRENOM' => 'Maryse',
                'VIS_ADRESSE' => '7B r Gay Lussac',
                'VIS_CP' => '21000',
                'VIS_VILLE' => 'DIJON',
                'VIS_DATEEMBAUCHE' => '1995-03-09 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'SW',
            ),
            array(
                'VIS_MATRICULE' => 't47',
                'VIS_NOM' => 'Tiphagne',
                'VIS_PRENOM' => 'Patrick',
                'VIS_ADRESSE' => '7B r Gay Lussac',
                'VIS_CP' => '62000',
                'VIS_VILLE' => 'ARRAS',
                'VIS_DATEEMBAUCHE' => '1997-08-29 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'SW',
            ),
            array(
                'VIS_MATRICULE' => 't55',
                'VIS_NOM' => 'Tréhet',
                'VIS_PRENOM' => 'Alain',
                'VIS_ADRESSE' => '7D chem Barral',
                'VIS_CP' => '12000',
                'VIS_VILLE' => 'RODEZ',
                'VIS_DATEEMBAUCHE' => '1994-11-29 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'SW',
            ),
            array(
                'VIS_MATRICULE' => 't60',
                'VIS_NOM' => 'Tusseau',
                'VIS_PRENOM' => 'Josselin',
                'VIS_ADRESSE' => '63 r Bon Repos',
                'VIS_CP' => '28000',
                'VIS_VILLE' => 'CHARTRES',
                'VIS_DATEEMBAUCHE' => '1991-03-29 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'GY',
            ),
            array(
                'VIS_MATRICULE' => 'zzz',
                'VIS_NOM' => 'swiss',
                'VIS_PRENOM' => 'bourdin',
                'VIS_ADRESSE' => NULL,
                'VIS_CP' => NULL,
                'VIS_VILLE' => NULL,
                'VIS_DATEEMBAUCHE' => '2003-06-18 00:00:00',
                'SEC_CODE' => NULL,
                'LAB_CODE' => 'BC',
            ),
            ));
    }
}
